repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # Git style
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-vcs-permalinks
  - id: forbid-new-submodules
  # Common errors
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: CHANGELOG.md
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  # Cross platform
  - id: check-case-conflict
  - id: mixed-line-ending
    args: [--fix=lf]
  # Security
  - id: detect-aws-credentials
    args:
    - --allow-missing-credentials
  - id: detect-private-key
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.23.3
  hooks:
  - id: gitleaks
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
  - id: yamllint
    types:
    - file
    - yaml
    args:
    - --strict
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shfmt
    args:
    - -l
    - -i
    - '2'
    - -ci
    - -sr
    - -w
  - id: shellcheck
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 1.97.3
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_docs
